 server:
# 设置项目启动的端口号
  port: 8080
# 设置项目的访问路径（上下文路径）
  servlet:
   context-path: /springboot01
## 数据源配置
 spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shujuku?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
## mybatis 配置
 mybatis:
#映射文件的存放路径
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.po
  configuration:
## 下划线转驼峰配置
    map-underscore-to-camel-case: true
## pageHelper
 pagehelper:
  helper-dialect: mysql
## 显示dao 执行sql语句
 logging:
  level:
   com:
    xxxx:
     dao: debug

    freemarker:
      suffix: .ftl
      content-type: text/html #响应格式
      charset: UTF-8
      template-loader-path: classpath:/views/
